basePath: /
consumes:
- application/json
definitions:
  main.Recipe:
    properties:
      id:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      name:
        type: string
      publishedAt:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
host: localhost:3000
info:
  contact:
    email: tanveeshs@gmail.com
    name: Tanveesh Singh Chaudhery
  description: This is a recipes API Project.
  title: Recipes API
  version: 1.0.0
paths:
  /recipes:
    get:
      description: To Get All Recipes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Recipe'
            type: array
      tags:
      - recipes
  /recipes/{id}:
    put:
      description: Update Recipe
      parameters:
      - description: Id of Recipe
        format: string
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Recipe'
      tags:
      - recipes
produces:
- application/json
schemes:
- http
swagger: "2.0"
